use crate::error::AppResult;
use sqlx::postgres::PgPool;

pub async fn init_schema(pool: &PgPool) -> AppResult<()> {
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS users (
            user_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            account TEXT UNIQUE,
            password_hash TEXT,
            id_number TEXT NOT NULL UNIQUE,
            avatar_url TEXT,
            created_at TEXT,
            updated_at TEXT
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_users_id_number
        ON users(id_number)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE UNIQUE INDEX IF NOT EXISTS idx_users_account_unique
        ON users(account)
        WHERE account IS NOT NULL
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS bots (
            bot_id TEXT PRIMARY KEY,
            owner_id TEXT NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            avatar_url TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            token TEXT NOT NULL UNIQUE,
            secret TEXT NOT NULL,
            created_at TEXT,
            updated_at TEXT,
            FOREIGN KEY (owner_id) REFERENCES users(user_id)
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_bots_owner_id
        ON bots(owner_id)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS groups (
            group_id TEXT PRIMARY KEY,
            group_code TEXT UNIQUE,
            creator_id TEXT NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            avatar_url TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT,
            updated_at TEXT,
            FOREIGN KEY (creator_id) REFERENCES users(user_id)
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_groups_creator_id
        ON groups(creator_id)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_groups_group_code
        ON groups(group_code)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS group_members (
            group_id TEXT NOT NULL,
            member_id TEXT NOT NULL,
            member_type TEXT NOT NULL DEFAULT 'bot',
            joined_at TEXT,
            PRIMARY KEY (group_id, member_id),
            FOREIGN KEY (group_id) REFERENCES groups(group_id),
            FOREIGN KEY (member_id) REFERENCES bots(bot_id)
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_group_members_member_id
        ON group_members(member_id)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS messages (
            msg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id TEXT NOT NULL,
            sender_id TEXT NOT NULL,
            content TEXT NOT NULL,
            msg_type TEXT DEFAULT 'text',
            idempotency_key TEXT,
            created_at TEXT,
            FOREIGN KEY (group_id) REFERENCES groups(group_id),
            FOREIGN KEY (sender_id) REFERENCES bots(bot_id)
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_messages_group_id_created_at
        ON messages(group_id, created_at)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_sender_group_idempotency
        ON messages(sender_id, group_id, idempotency_key)
        WHERE idempotency_key IS NOT NULL
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS files (
            file_id TEXT PRIMARY KEY,
            owner_id TEXT NOT NULL,
            content_hash TEXT,
            filename TEXT NOT NULL,
            size INTEGER NOT NULL,
            mime_type TEXT NOT NULL,
            storage_path TEXT NOT NULL,
            created_at TEXT,
            FOREIGN KEY (owner_id) REFERENCES bots(bot_id)
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_files_owner_id
        ON files(owner_id)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_files_content_hash
        ON files(content_hash)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS file_uploaders (
            file_id TEXT NOT NULL,
            uploader_id TEXT NOT NULL,
            created_at TEXT,
            PRIMARY KEY (file_id, uploader_id),
            FOREIGN KEY (file_id) REFERENCES files(file_id),
            FOREIGN KEY (uploader_id) REFERENCES bots(bot_id)
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_file_uploaders_uploader_id
        ON file_uploaders(uploader_id)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS file_references (
            file_id TEXT NOT NULL,
            reference_type TEXT NOT NULL,
            reference_id TEXT NOT NULL,
            created_at TEXT,
            PRIMARY KEY (file_id, reference_type, reference_id),
            FOREIGN KEY (file_id) REFERENCES files(file_id)
        )
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    sqlx::query(
        r#"
        CREATE INDEX IF NOT EXISTS idx_file_references_type_ref_id
        ON file_references(reference_type, reference_id)
        "#,
    )
    .execute(pool)
    .await
    .map_err(|e| crate::error::AppError::DatabaseError(e.to_string()))?;

    Ok(())
}
